name: teknisiku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.5.0
  geocoding: ^4.0.0
  geolocator: ^14.0.3
  http: ^1.6.0
  image_picker: ^1.2.0
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.example
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/illustrations/
    - assets/placeholders/
